"""URL routes para vistas basadas en templates.

Agrupa todas las rutas CRUD y listas con filtros para cada entidad.
"""
from django.urls import path
from .views_templates import (
    EspecialidadListView,
    EspecialidadCreateView,
    EspecialidadUpdateView,
    EspecialidadDeleteView,
    PacienteListView,
    PacienteCreateView,
    PacienteUpdateView,
    PacienteDeleteView,
    MedicoListView,
    MedicoCreateView,
    MedicoUpdateView,
    MedicoDeleteView,
    ConsultaListView,
    ConsultaCreateView,
    ConsultaUpdateView,
    ConsultaDeleteView,
    TratamientoListView,
    TratamientoCreateView,
    TratamientoUpdateView,
    TratamientoDeleteView,
    RecetaListView,
    RecetaCreateView,
    RecetaUpdateView,
    RecetaDeleteView,
    LaboratorioListView,
    LaboratorioCreateView,
    LaboratorioUpdateView,
    LaboratorioDeleteView,
    MedicamentoListView,
    MedicamentoCreateView,
    MedicamentoUpdateView,
    MedicamentoDeleteView,
    HistoriaListView,
    HistoriaCreateView,
    HistoriaUpdateView,
    HistoriaDeleteView,
    HomeView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('especialidades/', EspecialidadListView.as_view(), name='especialidad_list'),
    path('especialidades/nueva/', EspecialidadCreateView.as_view(), name='especialidad_create'),
    path('especialidades/<int:pk>/editar/', EspecialidadUpdateView.as_view(), name='especialidad_update'),
    path('especialidades/<int:pk>/borrar/', EspecialidadDeleteView.as_view(), name='especialidad_delete'),
    path('pacientes/', PacienteListView.as_view(), name='paciente_list'),
    path('pacientes/nuevo/', PacienteCreateView.as_view(), name='paciente_create'),
    path('pacientes/<int:pk>/editar/', PacienteUpdateView.as_view(), name='paciente_update'),
    path('pacientes/<int:pk>/borrar/', PacienteDeleteView.as_view(), name='paciente_delete'),
    path('medicos/', MedicoListView.as_view(), name='medico_list'),
    path('medicos/nuevo/', MedicoCreateView.as_view(), name='medico_create'),
    path('medicos/<int:pk>/editar/', MedicoUpdateView.as_view(), name='medico_update'),
    path('medicos/<int:pk>/borrar/', MedicoDeleteView.as_view(), name='medico_delete'),
    path('consultas/', ConsultaListView.as_view(), name='consulta_list'),
    path('consultas/nueva/', ConsultaCreateView.as_view(), name='consulta_create'),
    path('consultas/<int:pk>/editar/', ConsultaUpdateView.as_view(), name='consulta_update'),
    path('consultas/<int:pk>/borrar/', ConsultaDeleteView.as_view(), name='consulta_delete'),
    path('tratamientos/', TratamientoListView.as_view(), name='tratamiento_list'),
    path('tratamientos/nuevo/', TratamientoCreateView.as_view(), name='tratamiento_create'),
    path('tratamientos/<int:pk>/editar/', TratamientoUpdateView.as_view(), name='tratamiento_update'),
    path('tratamientos/<int:pk>/borrar/', TratamientoDeleteView.as_view(), name='tratamiento_delete'),
    path('recetas/', RecetaListView.as_view(), name='receta_list'),
    path('recetas/nueva/', RecetaCreateView.as_view(), name='receta_create'),
    path('recetas/<int:pk>/editar/', RecetaUpdateView.as_view(), name='receta_update'),
    path('recetas/<int:pk>/borrar/', RecetaDeleteView.as_view(), name='receta_delete'),
    path('laboratorios/', LaboratorioListView.as_view(), name='laboratorio_list'),
    path('laboratorios/nuevo/', LaboratorioCreateView.as_view(), name='laboratorio_create'),
    path('laboratorios/<int:pk>/editar/', LaboratorioUpdateView.as_view(), name='laboratorio_update'),
    path('laboratorios/<int:pk>/borrar/', LaboratorioDeleteView.as_view(), name='laboratorio_delete'),
    path('medicamentos/', MedicamentoListView.as_view(), name='medicamento_list'),
    path('medicamentos/nuevo/', MedicamentoCreateView.as_view(), name='medicamento_create'),
    path('medicamentos/<int:pk>/editar/', MedicamentoUpdateView.as_view(), name='medicamento_update'),
    path('medicamentos/<int:pk>/borrar/', MedicamentoDeleteView.as_view(), name='medicamento_delete'),
    path('historias/', HistoriaListView.as_view(), name='historia_list'),
    path('historias/nueva/', HistoriaCreateView.as_view(), name='historia_create'),
    path('historias/<int:pk>/editar/', HistoriaUpdateView.as_view(), name='historia_update'),
    path('historias/<int:pk>/borrar/', HistoriaDeleteView.as_view(), name='historia_delete'),
]


